// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSdEFRf0iGx3_oC-LAAhwMm1SWZd6P4rg',
    appId: '1:297470818690:web:b1859513a6ab26f577f79b',
    messagingSenderId: '297470818690',
    projectId: 'fruit-hub-e6c96',
    authDomain: 'fruit-hub-e6c96.firebaseapp.com',
    storageBucket: 'fruit-hub-e6c96.firebasestorage.app',
    measurementId: 'G-K1R50HSY4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4kdz2KZLwA8DXPRiZ9UHi0Y_jbt8jFdw',
    appId: '1:297470818690:android:2f794df5f89c362777f79b',
    messagingSenderId: '297470818690',
    projectId: 'fruit-hub-e6c96',
    storageBucket: 'fruit-hub-e6c96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM9FKrJoeUV9iiMxNb82dtv6R2CcNR9YM',
    appId: '1:297470818690:ios:4fbb7aac002da8fb77f79b',
    messagingSenderId: '297470818690',
    projectId: 'fruit-hub-e6c96',
    storageBucket: 'fruit-hub-e6c96.firebasestorage.app',
    androidClientId: '297470818690-vvctl0257aam48uni6b4edbr2uto1ncu.apps.googleusercontent.com',
    iosClientId: '297470818690-eft22hdsq5jhqdad5q4ihivge8k34rt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM9FKrJoeUV9iiMxNb82dtv6R2CcNR9YM',
    appId: '1:297470818690:ios:4fbb7aac002da8fb77f79b',
    messagingSenderId: '297470818690',
    projectId: 'fruit-hub-e6c96',
    storageBucket: 'fruit-hub-e6c96.firebasestorage.app',
    androidClientId: '297470818690-vvctl0257aam48uni6b4edbr2uto1ncu.apps.googleusercontent.com',
    iosClientId: '297470818690-eft22hdsq5jhqdad5q4ihivge8k34rt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSdEFRf0iGx3_oC-LAAhwMm1SWZd6P4rg',
    appId: '1:297470818690:web:2d1ee4df23b0886977f79b',
    messagingSenderId: '297470818690',
    projectId: 'fruit-hub-e6c96',
    authDomain: 'fruit-hub-e6c96.firebaseapp.com',
    storageBucket: 'fruit-hub-e6c96.firebasestorage.app',
    measurementId: 'G-J00BCS4DCN',
  );
}
